# Repartitioning runs on Azure Pipelines, because that's where we have SSH
# access to the download server.

name: $(Date:yyyyMMdd).$(Rev:r)

# Do not run automatically
trigger: none


parameters:
- name: Publish
  displayName: "Publish"
  type: boolean
  default: false
- name: TestPublish
  displayName: "Run all steps (including signing) without publishing"
  type: boolean
  default: false

stages:
- stage: PyManagerIndexPartition
  displayName: 'Repartition PyManager Index'

  jobs:
  - job: Repartition

    pool:
      vmImage: 'windows-latest'

    variables:
    - group: PythonOrgPublish
    - ${{ if or(eq(parameters.Publish, 'true'), eq(parameters.TestPublish, 'true')) }}:
      - group: CPythonSign

    steps:
    - checkout: self

    - task: NugetToolInstaller@0
      displayName: 'Install Nuget'

    - powershell: |
        nuget install -o host_python -x -noninteractive -prerelease python
        Write-Host "##vso[task.prependpath]$(gi host_python\python\tools)"
      displayName: 'Install host Python'
      workingDirectory: $(Build.BinariesDirectory)

    - powershell: |
        cd (mkdir -Force index)
        python "$(Build.SourcesDirectory)\scripts\repartition-index.py" --windows-default
        # Show the report
        cat index-windows.txt
      displayName: 'Repartition index'
      workingDirectory: $(Build.BinariesDirectory)

    - ${{ if or(eq(parameters.Publish, 'true'), eq(parameters.TestPublish, 'true')) }}:
      - powershell: |
          git clone https://github.com/python/cpython-bin-deps --revision fb06137dccc43ed5b030cdd9e3560990b37f39da --depth 1 --progress -v "signtool"
          "##vso[task.setvariable variable=MAKECAT]$(gi signtool\x64\makecat.exe)"
          "##vso[task.setvariable variable=SIGNTOOL]$(gi signtool\x64\signtool.exe)"
          "##vso[task.setvariable variable=DLIB]$(gi signtool\azure_trusted_signing\x64\Azure.CodeSigning.Dlib.dll)"
        workingDirectory: $(Pipeline.Workspace)
        displayName: 'Download signtool binaries'

      - task: AzureCLI@2
        displayName: 'Azure Login (1/2)'
        inputs:
          azureSubscription: 'Python Signing'
          scriptType: 'ps'
          scriptLocation: 'inlineScript'
          inlineScript: |
            "##vso[task.setvariable variable=AZURE_CLIENT_ID;issecret=true]${env:servicePrincipalId}" 
            "##vso[task.setvariable variable=AZURE_ID_TOKEN;issecret=true]${env:idToken}"
            "##vso[task.setvariable variable=AZURE_TENANT_ID;issecret=true]${env:tenantId}"
          addSpnToEnvironment: true

      - powershell: >
          az login --service-principal
          -u $(AZURE_CLIENT_ID)
          --tenant $(AZURE_TENANT_ID)
          --allow-no-subscriptions
          --federated-token $(AZURE_ID_TOKEN)
        displayName: 'Azure Login (2/2)'

      - powershell: |
          python "$(Build.SourcesDirectory)\ci\sign-json.py" (dir *.json)
        displayName: 'Sign index files'
        workingDirectory: $(Build.BinariesDirectory)
        env:
          SIGN_TOOLS: $(Pipeline.Workspace)\sign_tools
          TRUSTED_SIGNING_URI: $(TrustedSigningUri)
          TRUSTED_SIGNING_ACCOUNT: $(TrustedSigningAccount)
          TRUSTED_SIGNING_CERTIFICATE_NAME: $(TrustedSigningCertificateName)

    - publish: $(Build.BinariesDirectory)\index
      artifact: index
      displayName: Publish index artifact

    - ${{ if or(eq(parameters.Publish, 'true'), eq(parameters.TestPublish, 'true')) }}:
      - ${{ if ne(parameters.TestPublish, 'true') }}:
        - task: DownloadSecureFile@1
          name: sshkey
          inputs:
            secureFile: pydotorg-ssh.ppk
          displayName: 'Download PuTTY key'

      - powershell: |
          git clone https://github.com/python/cpython-bin-deps --revision 9f9e6fc31a55406ee5ff0198ea47bbb445eeb942 --depth 1 --progress -v "putty"
          "##vso[task.prependpath]$(gi putty)"
        workingDirectory: $(Pipeline.Workspace)
        displayName: 'Download PuTTY binaries'

      - powershell: |
          python ci\upload.py
        displayName: 'Publish packages'
        env:
          UPLOAD_URL: $(PyDotOrgUrlPrefix)python/
          UPLOAD_DIR: $(Build.BinariesDirectory)\index
          UPLOAD_URL_PREFIX: $(PyDotOrgUrlPrefix)
          UPLOAD_PATH_PREFIX: $(PyDotOrgUploadPathPrefix)
          UPLOAD_HOST: $(PyDotOrgServer)
          UPLOAD_HOST_KEY: $(PyDotOrgHostKey)
          UPLOAD_USER: $(PyDotOrgUsername)
          UPLOADING_INDEX: true
          ${{ if eq(parameters.TestPublish, 'true') }}:
            NO_UPLOAD: 1
          ${{ else }}:
            UPLOAD_KEYFILE: $(sshkey.secureFilePath)
